# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyx < Formula
  desc "CLI for the Nyxory deployment platform"
  homepage "https://nyxory.com"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.6.0/nyx-v0.6.0-darwin-amd64.tar.gz"
      sha256 "5b34b2c6b8480d21f74af5ab0e1f9a39a353304ffee1fc08ed23fa32a0cd4ad1"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.6.0/nyx-v0.6.0-darwin-arm64.tar.gz"
      sha256 "fec43d59ebbe46347d2b438fc3ac8a8254eb21eeba0316d24b8777cd2e641994"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.6.0/nyx-v0.6.0-linux-amd64.tar.gz"
      sha256 "80a06aa378b1631a35e3875320b2904844305d71629c8b76e04c9ceb6b370540"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.6.0/nyx-v0.6.0-linux-arm64.tar.gz"
      sha256 "744b5efabcb3dcdcbd63a6c02deb207824895f4a4baef427e318a9ae17200b4c"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  test do
    system "#{bin}/nyx", "--version"
  end
end
