# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyx < Formula
  desc "CLI for the Nyxory deployment platform"
  homepage "https://nyxory.com"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.9.1/nyx-v0.9.1-darwin-amd64.tar.gz"
      sha256 "bde66a9c625b723babcedeb5c0842731e5a66ba5c501f77d0745e139e856c5bf"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.9.1/nyx-v0.9.1-darwin-arm64.tar.gz"
      sha256 "1ecf5cc51f4aa889302c2d74bbb77bdf70483baf88c36f5be34e27abf430feb6"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.9.1/nyx-v0.9.1-linux-amd64.tar.gz"
      sha256 "6643e3ecd8bd559ff2a8fd5af8a8bc2f3c2e5d85347c4a43699f7d546c9eaf48"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.9.1/nyx-v0.9.1-linux-arm64.tar.gz"
      sha256 "0e972ce79a003785020c1565d6bac75e111ead2d092ae4ff2d9a13390b196cbc"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  test do
    system "#{bin}/nyx", "--version"
  end
end
