# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nyx < Formula
  desc "CLI for the Nyxory deployment platform"
  homepage "https://nyxory.com"
  version "0.12.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.12.4/nyx-v0.12.4-darwin-amd64.tar.gz"
      sha256 "f15899653fd1321521e72f843eb9c03fdfb3bd62ce87e70705c09e6a3ea82731"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.12.4/nyx-v0.12.4-darwin-arm64.tar.gz"
      sha256 "dd039a8951bbbc8c07c98c6e4e580ddde7e60e4fd6e407cb667ae9fc0244aab1"

      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.12.4/nyx-v0.12.4-linux-amd64.tar.gz"
      sha256 "55e2ef3b545e31568cc7ecd60d3336f0a454d4a876a681a76bf41835e6dc4f12"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nyxory/homebrew-tap/releases/download/v0.12.4/nyx-v0.12.4-linux-arm64.tar.gz"
      sha256 "ff5bb39b02ec368737f58342d79d5570e0d305d081d079125278f5e6286da91b"
      define_method(:install) do
        bin.install 'nyx'
      end
    end
  end

  test do
    system "#{bin}/nyx", "--version"
  end
end
